config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/scipion-docker:
      branch: devel
      repo: https://github.com/EOSC-synergy/scipion-docker
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      github.com/EOSC-synergy/scipion-docker im_client:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-mauve-binturong.sh
        container: svcqc.dep_wiggy-brown-gerbil
timeout: 5400
